### ISSUE TITLE
Directly get the image bytes instead of saving it to a file

### ISSUE THREAD

**Issue by Dhravya** [27Saumya/dhravyapy#4]
There should be an option to directly get image bytes instead of saving it to a file, since discord bots will use this more and will be more convenient that way

**Comment by saumsy** [comment]
Sure.. there will be a `.io()` or `.bytes()` method returning the image bytes too.
Note: The `.save()` method would be still there and the `.io`/`.bytes` will be a new method. Is this fine @Dhravya

**Comment by Dhravya** [comment]
Yes ofc. The save is necessary

**Comment by Dhravya** [comment]
solved in #6
