### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by sifte** [27Saumya/dhravyapy#8]
## QoL Improvements

- Make a single class that has all the methods instead of making lots of classes for each single method.
- If you do not wanna do the above, convert all the methods that people can **use** into classmethods. That way they don't have to call the class to use a method.

### Optional
- Follow [PEP8](https://www.python.org/dev/peps/pep-0008/) for cleaner code.

### Memes
- Instead of making [multiple methods](https://github.com/27Saumya/dhravyapy/blob/master/dhravya/fun.py#L53-L76), make a kwarg that will decide whether or not they want a single meme.
  
### Comments
Why was the folder `dhravyapy` changed it's name to `dhravya`? How would this improve the wrapper?

**Comment by saumsy** [comment]
Yes... I am making it a classmethod... that is in-progress.. sure the kwarg will be made... and about the dhravya it was changed cuz was getting circular import errors... but in v1.0 it will be back to `dhravyapy` because the error was fixed.

Thanks!

**Comment by saumsy** [comment]
@sifte Most things done, will make a release soon and update on pypi too

**Comment by saumsy** [comment]
Everything's done!

Closing the issue.
